### PR TITLE
Upgrade to rails 4?

### PR DESCRIPTION
**Pull request by devvmh**
Hey @Connoropolous, what do you think of moving to rails 4? I'm getting some experience with RoR at work, so I started fiddling with this in a branch.

(Don't merge this yet, BTW. It's FAR from done)

### CODE REVIEW

**Comment by Connoropolous** [comment]
Devin!

lol. I don't even know where in the world you are at the moment!

But given that it's not really any kind of UI change, I'm totally happy
that Rails 4 be implemented instead of 3 :)

On Tue, Sep 15, 2015 at 8:35 AM, Devin Howard <notifications@github.com>
wrote:

> Hey @Connoropolous <https://github.com/Connoropolous>, what do you think
> of moving to rails 4? I'm getting some experience with RoR at work, so I
> started fiddling with this in a branch.
>
> (Don't merge this yet, BTW. It's FAR from done)
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/metamaps/metamaps_gen002/pull/411
> Commit Summary
>
>    - update Gemfile for rails 4
>    - some config changes for rails 4 found on the Internet
>    - asset precompiling simpler in rails 4
>    - remove match method from routes.rb
>    - secret_token => secret_key_base
>    - remove attr_accessible
>    - add jquery_ui to gemfile
>    - remove old jquery-ui file
>    - fix has_many relationships in map & mapping models for rails 4
>
> File Changes
>
>    - *M* Gemfile
>    <https://github.com/metamaps/metamaps_gen002/pull/411/files#diff-0>
>    (27)
>    - *M* Gemfile.lock
>    <https://github.com/metamaps/metamaps_gen002/pull/411/files#diff-1>
>    (269)
>    - *D* app/assets/javascripts/lib/jquery-ui-1.8.23.custom.min.js
>    <https://github.com/metamaps/metamaps_gen002/pull/411/files#diff-2>
>    (25)
>    - *M* app/controllers/metacode_sets_controller.rb
>    <https://github.com/metamaps/metamaps_gen002/pull/411/files#diff-3>
>    (4)
>    - *M* app/controllers/users_controller.rb
>    <https://github.com/metamaps/metamaps_gen002/pull/411/files#diff-4>
>    (4)
>    - *M* app/models/in_metacode_set.rb
>    <https://github.com/metamaps/metamaps_gen002/pull/411/files#diff-5>
>    (1)
>    - *M* app/models/map.rb
>    <https://github.com/metamaps/metamaps_gen002/pull/411/files#diff-6>
>    (7)
>    - *M* app/models/mapping.rb
>    <https://github.com/metamaps/metamaps_gen002/pull/411/files#diff-7>
>    (3)
>    - *M* app/models/metacode_set.rb
>    <https://github.com/metamaps/metamaps_gen002/pull/411/files#diff-8>
>    (1)
>    - *M* app/models/user.rb
>    <https://github.com/metamaps/metamaps_gen002/pull/411/files#diff-9>
>    (2)
>    - *M* config/application.rb
>    <https://github.com/metamaps/metamaps_gen002/pull/411/files#diff-10>
>    (14)
>    - *M* config/environments/development.rb
>    <https://github.com/metamaps/metamaps_gen002/pull/411/files#diff-11>
>    (15)
>    - *M* config/environments/production.rb
>    <https://github.com/metamaps/metamaps_gen002/pull/411/files#diff-12>
>    (3)
>    - *M* config/environments/test.rb
>    <https://github.com/metamaps/metamaps_gen002/pull/411/files#diff-13>
>    (8)
>    - *M* config/initializers/secret_token.rb
>    <https://github.com/metamaps/metamaps_gen002/pull/411/files#diff-14>
>    (2)
>    - *M* config/routes.rb
>    <https://github.com/metamaps/metamaps_gen002/pull/411/files#diff-15>
>    (36)
>
> Patch Links:
>
>    - https://github.com/metamaps/metamaps_gen002/pull/411.patch
>    - https://github.com/metamaps/metamaps_gen002/pull/411.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/metamaps/metamaps_gen002/pull/411>.
>



-- 
Connor Turland
~to craft a sustainable and thriving culture within and without myself~
co-creator of Metamaps.cc
JS Dev @ bitHound.io

**Comment by devvmh** [comment]
Haha China :D

Great! As I get the chance I'll work through testing it out on rails 4 and re-implementing broken features, then I'll ping you if I feel like it's ready

**Comment by devvmh** [comment]
@Connoropolous OK I think it's ready for some wider testing. Could we try deploying this to staging and asking others to stress test it? It would be great if you could take a look at the code changes too, very little actually changed

**Comment by Connoropolous** [comment]
I'm pulling it down and giving it a go.

Just took a quick look at the code

**Comment by Connoropolous** [comment]
apparently heroku suggests that we serve static assets from a CDN...
https://devcenter.heroku.com/articles/using-amazon-cloudfront-cdn

saw this here:
https://devcenter.heroku.com/articles/rails-4-asset-pipeline#only-generate-digest-assets

I've deployed rails 4 branch to the staging environment... http://metamaps.herokuapp.com/ but we are seeing assets issues. 
references to assets in our files look like they need to be referenced this way to work 
`<%= asset_path('logo.png') %>`

**Comment by Connoropolous** [comment]
hey @devvmh I think we should just merge this in... I have some other work that I want to do on metamaps, and I'd like to just build on top of this work, and test it in the process, the only thing really standing out as broken is in my last comment about the assets. What do you think?

**Comment by devvmh** [comment]
Sure! I was going to try to go through and change all the assets. My one
confusion still was whether you needed to replace assets like that if they
were added via javascript (e.g. in the html.erb file they show up as
src="{{metacode.icon}}" or something like that. Feel free to merge it in.

The other bit, though, is that I was pretty systematic about a few things,
but I wasn't systematic about testing things. It would be great if you did
some kind of comprehensive testing first. I could try to get a handle on
that.

Maybe even we should have some sort of "QA" scheme - you could give a word
document to someone that asks them to do 50 tasks, and by doing so they'll
cover most of the functionality of metamaps and find any errors in that
basic functionality.

I just haven't sat down with this for a few days. In my mind, it's
*probably* ready.... but I don't make any promises and if it were me I'd
test first.

**Comment by devvmh** [comment]
I just pushed a file with a bunch of things someone could do to test the interface minimally. It would be great to write rspec tests for this - maybe I'll do that sometime haha. But for now, when I get a chance, I'll do these steps to make sure I feel OK about it.

I also included in the push a couple of asset_path fixes.... but I haven't tested those actually work yet. So now we should definitely test the changes before pushing to production (if only to verify the spots I added asset_path still correctly render images)

**Comment by Connoropolous** [comment]
but how can rspec tests actually test the interface? we can test the backend stuff with tests, but not frontend so easily

**Comment by Connoropolous** [comment]
If you got started on it, I guess we can go ahead and change the rest of the asset paths before we merge it in :)

**Comment by devvmh** [comment]
Well, rspec can simulate all of the controller actions and make sure they
work. That'd really what I'm worried about from this change

If you do a quick run through of the interface and it works, I'd just go
ahead

**Comment by devvmh** [comment]
OK I fixed the last Javascript issue. Let's get testing on staging if possible. I'm going to try pushing to heroku momentarily

**Pull request merged**
