### PR TITLE
Run tests on Travis CI; show build status badge

### PR DESCRIPTION
**Pull request by harlantwood**
Set up Travis CI; switch build badge to use that.

Jenkins seems to be down at the moment; Travis is awesome.

@devvmh if you prefer, we could have status badges for both Jenkins and Travis...

### CODE REVIEW

**Comment by devvmh** [comment]
Sounds good to me! I didn't know you could just use Travis for free

What does Travis run? bundle exec rspec? How do you specify that? Is there a page with documentation?

Yeah, the Jenkins server is on cloudatcost.com, so not very reliable haha

**Comment by harlantwood** [comment]
Yup!  Free for open source.  

> What does Travis run? 

`bundle exec rake` by default:
https://docs.travis-ci.com/user/languages/ruby#Default-Test-Script

> How do you specify that? 

a `script` block I think?   not 100% sure.

**Comment by harlantwood** [comment]
BTW @devvmh were you exposing coverage reports on Jenkins?  Haven't thought yet about how to do that on Travis, but would be nice.

**Comment by harlantwood** [comment]
@Connoropolous I encourage you to merge this soon... It will build all branches and PR's by default, and let you know if you are "green" to merge a PR, which should be quite helpful.

Steps:
- [ ] visit https://travis-ci.org/profile/metamaps and turn on builds for this repo
- [ ] merge this PR
- [ ] awesome! Every new commit should be built on Travis, and the readme badge should link there

**Pull request merged**
