### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by devvmh**
Thoughts?

### CODE REVIEW

**Comment by Connoropolous** [comment]
is this still relevant @devvmh

**Comment by devvmh** [comment]
Yes it's recent

**Comment by devvmh** [comment]
Updated this to be less annoying, rebased better on to master, and figured out 80 columns better. I also decided on breaking lines at 80 characters rather than just writing full paragraphs. I hope it looks OK...

And geez! Jenkins works! This check won't pass since the master branch doesn't have the integration set up yet.

I'll merge this just to get it out of the list unless there are objections.

**Comment by devvmh** [comment]
@poietic @Connoropolous

**Comment by Connoropolous** [comment]
@devvmh you are rocking it. merge this one too

**Pull request merged**
