### PR TITLE
merge develop into master (version 2.8!)

### PR DESCRIPTION
**Pull request by Connoropolous**
Just opening this up so we start making a little of record of what it's going to take to deploy ALL THESE FEATURES

- [ ] test all features on the staging website
- [ ] test migrations on a copy of the database
- [ ] deploy
- [ ] run migrations on prod
- [ ] run rake task for metacodes as per https://github.com/metamaps/metamaps_gen002/commit/295534e4abf084b839f595427912b72f598aee8c
- [ ] start a `bundle exec rake jobs:work` process on prod now, to handle jobs

### CODE REVIEW

**Comment by Connoropolous** [comment]
@devvmh ... actually, it might make the most sense to deploy these things without video stuff in them first, because it's a lot. Then I'll work on merging this stuff into my video branch, then we'll push that out later this week?

**Comment by Connoropolous** [comment]
There's a thing where the search bar isn't expanded when you're on the explore map pages, like `/`, and it's supposed to be

**Comment by Connoropolous** [comment]
```
Started GET "/topics/18/network.json" for 10.0.2.2 at 2016-03-13 01:17:42 +0000
Processing by TopicsController#network as JSON
  Parameters: {"id"=>"18"}
Completed 500 Internal Server Error in 67ms (ActiveRecord: 1.7ms)

NoMethodError (undefined method `where' for #<Array:0x007f562c7020e0>):
  app/policies/topic_policy.rb:7:in `resolve'
  app/controllers/topics_controller.rb:44:in `network'
```

**Comment by Connoropolous** [comment]
Well, we definitely have a bunch of tests to fix :(

**Comment by harlantwood** [comment]
On the good side, we have a bunch of tests : )

**Comment by devvmh** [comment]
@Connoropolous you can delete the failing permissions tests re "authorize to edit". I'm working on new ones on the pundit branch

I guess I didn't delete those functions out of the models yet either. I'll do it if you don't first

**Comment by Connoropolous** [comment]
Actually they're failing because I deleted those functions out of the
models. I have another bug to fix so if you could delete those tests it'd
be great

On Monday, March 14, 2016, Devin Howard <notifications@github.com> wrote:

> @Connoropolous <https://github.com/Connoropolous> you can delete the
> failing permissions tests re "authorize to edit". I'm working on new ones
> on the pundit branch
>
> I guess I didn't delete those functions out of the models yet either. I'll
> do it if you don't first
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/metamaps/metamaps_gen002/pull/482#issuecomment-196115730>
> .
>


-- 
Connor Turland
~to craft a sustainable and thriving culture within and without myself~
co-creator of Metamaps.cc

**Comment by devvmh** [comment]
@Connoropolous Let me know when develop gets up on staging!

**Comment by Connoropolous** [comment]
It's up now :)

**Pull request merged**
