### PR TITLE
remove cancan dependency

### PR DESCRIPTION
**Pull request by devvmh**
ok @Connoropolous I've been looking again. We really shouldn't need cancan. Snorlax depends on cancancan, which we have in our Gemfile.lock because of the snorlax dependency. cancan is deprecated, so it'd be great to get it out.

What was the specific problem that required cancan? I'll take a stab at fixing it and add it to this branch.

### CODE REVIEW

**Comment by devvmh** [comment]
I started looking at this but I can't even figure out how to get a token!!

**Comment by Connoropolous** [comment]
I believe the issue stems from here

https://github.com/loomio/snorlax/blob/b4b778cf1c4afb9cbfdfa91d9bae17848251a4d2/app/controllers/snorlax/base.rb#L6

**Comment by Connoropolous** [comment]
to get a token: look for the code block in this comment https://github.com/metamaps/metamaps_gen002/pull/481#issue-140105499

**Comment by devvmh** [comment]
@Connoropolous check out my latest commit, i think i got it fixed

**Comment by Connoropolous** [comment]
solid, if it works, I'm happy

**Comment by devvmh** [comment]
could you test? I'm really not sure if it works.

I'm also submitting a PR to snorlax in a bit

**Comment by Connoropolous** [comment]
Yes, I'll test

**Comment by devvmh** [comment]
switching to #499

**Pull request closed without merging**
