### PR TITLE
create synapse if you click away from the synapse title form

### PR DESCRIPTION
**Pull request by devvmh**
This pull request is not a priority. It needs UX discussion. But you'll notice that the code isn't too involved to enable this feature.

I thought when writing this code long ago that it made making a map smoother. But I don't map as much as others so I'd be interested in feedback. I can push this to staging sometime if anyone is interested (probably once realtime video is done!)

### CODE REVIEW

**Comment by devvmh** [comment]
@poietic can you help with this pull request?

I have to verify the actual code's behaviour still, but the idea is this:

Currently, if you are creating a blank (no description) synapse and hit Enter, it creates the synapse. But if you click the canvas or hit Tab, it doesn't create it. This would modify the behaviour to create synapses by default. 

I think this makes it easier to create connections, but puts less emphasis on labelling those connections.

Should we merge this with the realtime changes, move it to a later release, or close it?

**Comment by poietic** [comment]
if its done, lets merge it with the realtime changes so we can test it out!

On Sun, Feb 7, 2016 at 1:45 AM, Devin Howard <notifications@github.com>
wrote:

> @poietic <https://github.com/poietic> can you help with this pull request?
>
> I have to verify the actual code's behaviour still, but the idea is this:
>
> Currently, if you are creating a blank (no description) synapse and hit
> Enter, it creates the synapse. But if you click the canvas or hit Tab, it
> doesn't create it. This would modify the behaviour to create synapses by
> default.
>
> I think this makes it easier to create connections, but puts less emphasis
> on labelling those connections.
>
> Should we merge this with the realtime changes, move it to a later
> release, or close it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/metamaps/metamaps_gen002/pull/447#issuecomment-180984297>
> .
>



-- 
Ishan M. Shapiro
co-founder
Metamaps.cc <http://metamaps.cc/> | Notthisbody <http://notthisbody.com>
@metamapps <http://twitter.com/metamapps> | @notthisbody
<http://twitter.com/notthisbody>
<http://cargo.notthisbody.com>

**Comment by Connoropolous** [comment]
+1

**Comment by devvmh** [comment]
OK this can be deployed together with realtime video

**Pull request merged**
