### PR TITLE
install dotenv to help managed env vars

### PR DESCRIPTION
**Pull request by mixmix**
[dotenv](https://github.com/bkeepers/dotenv) is a nice gem that looks for a `.env` file and exports all the variables in there. 

you can keep a list of all the env (like in the .example-env) so that new people setting up your project have an idea of what they might need to configure.

I've pre-populated yours using the command at the bottom of the file

### CODE REVIEW

**Comment by harlantwood** [comment]
+1 dotenv rocks.

**Comment by Connoropolous** [comment]
@devvmh we should try and get this merged in too :)

**Comment by Connoropolous** [comment]
@mixmix :) sorry that it has taken us as long as it has to respond on this. would you be willing to reopen the PR, but to the 'develop' branch?

**Comment by devvmh** [comment]
I forked a fork and merged it into develop, using the commit authored by mix mix :)

**Comment by mixmix** [comment]
Thanks for that, I've been off net traveling

**Pull request closed without merging**
