### PR TITLE
first 2 slack events

### PR DESCRIPTION
**Pull request by Connoropolous**
- [x] get basics working
- [x] add migration for events
- [x] add migration for webhooks

### CODE REVIEW

**Comment by devvmh** [comment]
I vote we push it to production with no UI. I don't think anyone is waiting for this, but having it in slack will be great for us to start, and help us think about UI design based on our real usage.

Would you like me to merge develop into this branch?

**Comment by poietic** [comment]
+1 i'm cool w/ that. lets bring metamaps back into alpha! hehehe

On Tue, Feb 16, 2016 at 7:47 PM, Devin Howard <notifications@github.com>
wrote:

> I vote we push it to production with no UI. I don't think anyone is
> waiting for this, but having it in slack will be great for us to start, and
> help us think about UI design based on our real usage.
>
> Would you like me to merge develop into this branch?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/metamaps/metamaps_gen002/pull/418#issuecomment-185004703>
> .
>



-- 
Ishan M. Shapiro
co-founder
Metamaps.cc <http://metamaps.cc/> | Notthisbody <http://notthisbody.com>
@metamapps <http://twitter.com/metamapps> | @notthisbody
<http://twitter.com/notthisbody>
<http://cargo.notthisbody.com>

**Comment by devvmh** [comment]
Haha, the only conflict was the Gemfile, so I just merged it.

**Comment by Connoropolous** [comment]
Sweet Devin :) thanks for updating it. For future reference, my take on the
best way to keep branches up to date is by doing rebases, so that
ultimately the clutter of merge commits is avoided. Definitely not a huge
deal though.

Anyways, yeah, it'd be awesome to deploy it and test it out, do some
iteration from there. Right now theres an unneccesarry addition of a job
scheduled gem and db columns, which ought to be removed before it goes in.

**Comment by devvmh** [comment]
Yeah, feel free to rebase. The problem with rebasing is force pushing; if you rebase a branch locally it's easy, but if you rebase one on origin you don't know who's checked it out and made their own changes. Rebases can screw that up.

But I don't have any other copies of this branch, and I doubt anyone else does, so go for it if you like

**Comment by Connoropolous** [comment]
Right, I see. Naw I won't worry about.

**Pull request merged**
